### ISSUE TITLE
Copying permalink

### ISSUE THREAD

**Issue by rfay** [rfay/junker99-rfay#5]
How about this:?
https://github.com/drud/ddev/blob/4ca6d38aa2158595160231fd3ac7aeec2501f3bc/pkg/plugins/platform/utils.go#L47-L56

**Comment by rfay** [comment]
How about this?
 
https://github.com/drud/ddev/blob/4ca6d38aa2158595160231fd3ac7aeec2501f3bc/pkg/plugins/platform/utils.go#L47-L56

**Comment by beeradb** [comment]
https://github.com/rfay/junker99-rfay/blob/a05a08eb019c14586bbd97761e86d74204c53027/circle.yml#L3-L7
